### ISSUE TITLE
[Feature] : Setup the environment

### ISSUE THREAD

**Issue by hocine1212** [202306-NEA-DZ-FEW/e-commerce-project-souqdz#2]
**Please Describe the feature.**
Set up the folders structure and install daisyUI. 
**Describe the solution you'd like**
Create the folder layout and install daisyUI library for styling purposes.
**Describe alternatives you've considered**
No alternatives for the moment
**Additional context**
No additional context

**Comment by hasnahadd** [comment]
done 🎉
